package team.kitemc.verifymc.web;

public enum ErrorCode {
    INVALID_REQUEST("INVALID_REQUEST"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    NOT_FOUND("NOT_FOUND"),
    INTERNAL_ERROR("INTERNAL_ERROR"),
    
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS"),
    USER_BANNED("USER_BANNED"),
    
    INVALID_USERNAME("INVALID_USERNAME"),
    INVALID_EMAIL("INVALID_EMAIL"),
    INVALID_UUID("INVALID_UUID"),
    INVALID_PASSWORD("INVALID_PASSWORD"),
    EMAIL_DOMAIN_NOT_ALLOWED("EMAIL_DOMAIN_NOT_ALLOWED"),
    EMAIL_ALIAS_NOT_ALLOWED("EMAIL_ALIAS_NOT_ALLOWED"),
    EMAIL_LIMIT_EXCEEDED("EMAIL_LIMIT_EXCEEDED"),
    USERNAME_EXISTS("USERNAME_EXISTS"),
    USERNAME_CASE_CONFLICT("USERNAME_CASE_CONFLICT"),
    
    INVALID_CAPTCHA("INVALID_CAPTCHA"),
    CAPTCHA_EXPIRED("CAPTCHA_EXPIRED"),
    INVALID_VERIFY_CODE("INVALID_VERIFY_CODE"),
    VERIFY_CODE_RATE_LIMITED("VERIFY_CODE_RATE_LIMITED"),
    
    QUESTIONNAIRE_REQUIRED("QUESTIONNAIRE_REQUIRED"),
    QUESTIONNAIRE_NOT_PASSED("QUESTIONNAIRE_NOT_PASSED"),
    QUESTIONNAIRE_EXPIRED("QUESTIONNAIRE_EXPIRED"),
    QUESTIONNAIRE_INVALID("QUESTIONNAIRE_INVALID"),
    
    DISCORD_LINK_FAILED("DISCORD_LINK_FAILED"),
    DISCORD_NOT_IN_GUILD("DISCORD_NOT_IN_GUILD"),
    DISCORD_REQUIRED("DISCORD_REQUIRED"),
    
    REVIEW_FAILED("REVIEW_FAILED"),
    INVALID_REVIEW_ACTION("INVALID_REVIEW_ACTION");
    
    private final String code;
    
    ErrorCode(String code) {
        this.code = code;
    }
    
    public String getCode() {
        return code;
    }
}
